### ISSUE TITLE
camera distortion parameters need to be in CameCase

### ISSUE THREAD

**Issue by christian-rauch** [JimmyDaSilva/gazebo_kinect_sim#1]
The camera distortion parameters in the `model.sdf` are given as `distortion_k1`, `distortion_k2`, etc. but the plugin expects the names `distortionK1`, `distortionK2`,etc. As a result chaging only the values in the SDF will not change them in the plugin. This can be seen of DEBUG output for `gazebo_plugins` is activated:
```
Camera plugin missing <distortionK1>, defaults to 0
Camera plugin missing <distortionK2>, defaults to 0
Camera plugin missing <distortionK3>, defaults to 0
Camera plugin missing <distortionT1>, defaults to 0
Camera plugin missing <distortionT2>, defaults to 0
```

**Comment by JimmyDaSilva** [comment]
Hi @christian-rauch and thanks for opening the issue.
It was definitely `<distortion_k1>` before. I guess it comes with the new versions of Gazebo 8 or 9.
I need to check since when this change applies.

Thanks again !

**Comment by JimmyDaSilva** [comment]
It seems the change comes from a long time ago, so I changed it on the master branch.
So should be fixed with https://github.com/kuka-isir/gazebo_kinect_sim/commit/39c7a468bf5d30322072c355b03a5bd1b59d57db 

Thanks again !
